apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: helm/kyverno-policies/charts/kyverno-policies
  contents:
  - path: .
    git:
      url: https://github.com/giantswarm/kyverno
      ref: v1.13.0
    includePaths:
      - charts/kyverno-policies/**
    newRootPath: charts/kyverno-policies
