{{ $name := "disallow-ephemeral-containers" }}
{{ if and (hasKey .Values.debugAccessPolicies.policies $name) (get .Values.debugAccessPolicies.policies $name).enabled }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: {{ printf "%s%s" .Values.policyNamePrefix $name }}
  labels: {{ include "labels.common" . | nindent 4 }}
  annotations:
    policies.kyverno.io/title: Block Ephemeral Containers
    policies.kyverno.io/category: Security
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: Ephemeral containers, enabled by default in Kubernetes 1.23, allow users to use the `kubectl debug` functionality and attach a temporary container to an existing Pod. This may potentially be used to gain access to unauthorized information executing inside one or more containers in that Pod. This policy blocks the use of ephemeral containers.
spec:
  validationFailureAction: {{ (get .Values.debugAccessPolicies.policies $name).mode }}
  background: true
  rules:
    - name: disallow-ephemeral-containers
      match:
        any:
          - resources:
              kinds:
                - Pod
              operations:
                - CREATE
                - UPDATE
      validate:
        cel:
          expressions:
            - expression: "!has(object.spec.ephemeralContainers)"
              message: Ephemeral (debug) containers are not permitted.
{{ end }}
